### ISSUE TITLE
libpq-dev installation issue

### ISSUE THREAD

**Issue by prvnkumark** [ncbi/python-libpq-dev#1]
Hi,

I am unable to install libpq-dev, i get below error message.

root@kali:~# pip install libpq-dev==9.4.3
Downloading/unpacking libpq-dev==9.4.3
  Could not find any downloads that satisfy the requirement libpq-dev==9.4.3
Cleaning up...
No distributions at all found for libpq-dev==9.4.3
Storing debug log for failure in /root/.pip/pip.log

Content of pip.log
## root@kali:~# cat /root/.pip/pip.log 

/usr/bin/pip run on Mon Dec 28 11:37:30 2015
Downloading/unpacking libpq-dev
  Getting page https://pypi.python.org/simple/libpq-dev/
  URLs to search for versions for libpq-dev:
- https://pypi.python.org/simple/libpq-dev/
  Analyzing links from page https://pypi.python.org/simple/libpq-dev/
  Could not find any downloads that satisfy the requirement libpq-dev
  Cleaning up...
  No distributions at all found for libpq-dev
  Exception information:
  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
  DistributionNotFound: No distributions at all found for libpq-dev

**Comment by dmnapolitano** [comment]
Howdy, same exact issue here:

```
$ pip install libpq-dev==9.3.10
Collecting libpq-dev==9.3.10
  Could not find a version that satisfies the requirement libpq-dev==9.3.10 (from versions: )
No matching distribution found for libpq-dev==9.3.10
```

`pip` version 7.1.2.  I think your post to `pypi` is missing the actual package(s) :confused:

**Comment by Shekharrajak** [comment]
```
~# pip install libpq-dev==9.4.3
Collecting libpq-dev==9.4.3
  Could not find a version that satisfies the requirement libpq-dev==9.4.3 (from versions: )
No matching distribution found for libpq-dev==9.4.3

```

**Comment by PrometheusPi** [comment]
one way to go from there is:
 - clone the repo
 - build the PG binaries of version 9.4.1 via `./build.sh 9.4.1`
 - install the binaries via `cd dist && pip install *.whl`
 - install psycopg2 via: `pip install psycopg2`

**Comment by wen-dell** [comment]
I have a simpler solution. If you use a Linux OS, you can install libpq-dev via terminal. So, just use this command: `sudo apt install libpq-dev`.

**Comment by ismailsunni** [comment]
I stumbled this issue when I tried to install `libpq-dev`:
```
The following packages have unmet dependencies:
 libpq-dev : Depends: libpq5 (= 10.12-0ubuntu0.18.04.1) but 12.3-1.pgdg18.04+1 is to be installed
```

any suggestions to fix this?

Thanks!

**Comment by EdwardNgo** [comment]
> I stumbled this issue when I tried to install `libpq-dev`:
> 
> ```
> The following packages have unmet dependencies:
>  libpq-dev : Depends: libpq5 (= 10.12-0ubuntu0.18.04.1) but 12.3-1.pgdg18.04+1 is to be installed
> ```
> 
> any suggestions to fix this?
> 
> Thanks

Have you fixed that problem ?

**Comment by ismailsunni** [comment]
@EdwardNgo yes,

In my case, I need to install a specific version of `libpq5`
```
sudo apt install libpq5=10.12-0ubuntu0.18.04.1
```

**Comment by EdwardNgo** [comment]
> @EdwardNgo yes,
> 
> In my case, I need to install a specific version of `libpq5`
> 
> ```
> sudo apt install libpq5=10.12-0ubuntu0.18.04.1
> ```

Thank you for helping me. That worked

**Comment by winsont1** [comment]
> ```
> sudo apt install libpq5=10.12-0ubuntu0.18.04.1
> ```

Use the latest version here and it should work :)
 https://www.ubuntuupdates.org/package/core/bionic/main/proposed/libpq5

**Comment by K-N-A-R-G** [comment]
>Use the latest version here and it should work :)
https://www.ubuntuupdates.org/package/core/bionic/main/proposed/libpq5

This doesn't work at all.
```
sudo apt install --upgrade libpq5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpq5 : Depends: libldap-2.4-2 (>= 2.4.7) but it is not installable
          Depends: libssl1.1 (>= 1.1.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
